# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kadem/proto/hash_node.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kadem.proto import ping_request_pb2 as kadem_dot_proto_dot_ping__request__pb2
from kadem.proto import ping_response_pb2 as kadem_dot_proto_dot_ping__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bkadem/proto/hash_node.proto\x1a\x1ekadem/proto/ping_request.proto\x1a\x1fkadem/proto/ping_response.proto21\n\x08HashNode\x12%\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kadem.proto.hash_node_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HASHNODE._serialized_start=96
  _HASHNODE._serialized_end=145
# @@protoc_insertion_point(module_scope)
