# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kadem.proto import ping_request_pb2 as kadem_dot_proto_dot_ping__request__pb2
from kadem.proto import ping_response_pb2 as kadem_dot_proto_dot_ping__response__pb2


class HashNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/HashNode/Ping',
                request_serializer=kadem_dot_proto_dot_ping__request__pb2.PingRequest.SerializeToString,
                response_deserializer=kadem_dot_proto_dot_ping__response__pb2.PingResponse.FromString,
                )


class HashNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HashNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=kadem_dot_proto_dot_ping__request__pb2.PingRequest.FromString,
                    response_serializer=kadem_dot_proto_dot_ping__response__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HashNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HashNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HashNode/Ping',
            kadem_dot_proto_dot_ping__request__pb2.PingRequest.SerializeToString,
            kadem_dot_proto_dot_ping__response__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
